
import Head from "next/head";
import TopLeftImg from "./TopLeftImg"
import Nav from "./Nav"
import Header from "./Header"
import Circles from './Circles';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1, maximum-scale=1', // <-- here
}


const Layout = ({ children, fontSora }) => {
  return <>
    <div className={`page bg-site text-white bg-cover h-dvh bg-no-repeat ${fontSora.variable}`}>
      <div className=" bg-gradient-to-r from-primary/10 via-black/30 to-black/10 h-full justify-between flex flex-col">
        <TopLeftImg />
        <Header />
        {children}
        <Nav />
        <Circles />
      </div>
    </div>
  </>
};

export default Layout;
